ktor {
    development = true

    deployment {
        port = 8080
    }
    application {
        modules = [com.rooter.aipoc.BootstrapperKt.appEntryModule]
    }
}

ai {
    geminiApiKey = ${?GEMINI_API_KEY}
    modelReasoning = "gemini-3.1-flash-lite"
    modelReasoning = ${?GEMINI_MODEL_REASONING}
    modelFast = "gemini-3.1-flash-lite"
    modelFast = ${?GEMINI_MODEL_FAST}
}
